- hosts: localhost
  become: true
  pre_tasks:
  - name: Update system cache
    apt:
      update_cache: true
    tags:
    - node
    - zsh
  tasks:
  - include: tasks/node.yml
  - include: tasks/zsh.yml 